#!/usr/bin/env bash
# =============================================================
# Postiz – Hostinger VPS Deployment Script
# Usage: bash deploy.sh
# =============================================================
set -euo pipefail

REPO_URL="https://github.com/Captainjacksparrow93/Postiz.git"
APP_DIR="/opt/postiz"

echo "=============================="
echo "  Postiz VPS Deployment"
echo "=============================="

# ── 1. Install Docker if missing ──────────────────────────────
if ! command -v docker &>/dev/null; then
  echo "[1/5] Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker
  systemctl start docker
else
  echo "[1/5] Docker already installed – skipping."
fi

# ── 2. Clone or pull the repo ─────────────────────────────────
if [ -d "$APP_DIR/.git" ]; then
  echo "[2/5] Pulling latest code..."
  git -C "$APP_DIR" pull
else
  echo "[2/5] Cloning repo..."
  git clone "$REPO_URL" "$APP_DIR"
fi

cd "$APP_DIR"

# ── 3. Auto-detect public IP and create/patch .env ───────────
echo "[3/5] Configuring environment..."

# Detect public IP of this VPS
PUBLIC_IP=$(curl -s --max-time 5 ifconfig.me \
  || curl -s --max-time 5 icanhazip.com \
  || curl -s --max-time 5 api.ipify.org \
  || echo "72.62.248.38")

MAIN_URL="http://${PUBLIC_IP}:4007"
BACKEND_URL="http://${PUBLIC_IP}:4007/api"

if [ ! -f ".env" ]; then
  echo "  .env not found – generating one for this VPS..."

  # Generate a random JWT secret
  JWT_SECRET=$(tr -dc 'A-Za-z0-9!@#%^&*()-_=+' </dev/urandom | head -c 64 || \
               cat /proc/sys/kernel/random/uuid | tr -d '-' | head -c 64)
  POSTGRES_PASSWORD=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32 || echo "postiz-secure-$(date +%s)")

  cat > .env <<EOF
# === Postiz – auto-generated by deploy.sh ===
MAIN_URL=${MAIN_URL}
FRONTEND_URL=${MAIN_URL}
NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}
BACKEND_INTERNAL_URL=http://localhost:3000

JWT_SECRET=${JWT_SECRET}

POSTGRES_USER=postiz-user
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=postiz-db-local

STORAGE_PROVIDER=local
UPLOAD_DIRECTORY=/uploads
NEXT_PUBLIC_UPLOAD_DIRECTORY=/uploads

IS_GENERAL=true
DISABLE_REGISTRATION=false
EOF

  echo "  .env created with IP: ${PUBLIC_IP}"
else
  echo "  .env found – patching URLs to match this VPS IP (${PUBLIC_IP})..."

  # Always keep the URL vars pointing at the actual VPS IP
  sed -i "s|^MAIN_URL=.*|MAIN_URL=${MAIN_URL}|"                         .env
  sed -i "s|^FRONTEND_URL=.*|FRONTEND_URL=${MAIN_URL}|"                 .env
  sed -i "s|^NEXT_PUBLIC_BACKEND_URL=.*|NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}|" .env

  # Add the keys if they are missing entirely
  grep -q '^MAIN_URL='                 .env || echo "MAIN_URL=${MAIN_URL}"                 >> .env
  grep -q '^FRONTEND_URL='             .env || echo "FRONTEND_URL=${MAIN_URL}"             >> .env
  grep -q '^NEXT_PUBLIC_BACKEND_URL='  .env || echo "NEXT_PUBLIC_BACKEND_URL=${BACKEND_URL}" >> .env

  echo "  URLs updated."
fi

# ── 4. Pull latest Docker images ─────────────────────────────
echo "[4/5] Pulling Docker images..."
docker compose pull

# ── 5. Start / restart services ──────────────────────────────
echo "[5/5] Starting services..."
docker compose down --remove-orphans 2>/dev/null || true
docker compose up -d

echo ""
echo "=============================="
echo "  Deployment complete!"
echo "  Visit: ${MAIN_URL}"
echo "=============================="
